#!/usr/bin/env python
from setup_utils import *
import os
import socket

# icat.server

def uninstall():
    app = actions.getAppName("icat.lucene")
    if app: actions.undeploy(app)
    
actions, arg, props = getActions("lucene-setup.properties", [])

prop_name = "lucene.properties"
prop_list = ["directory", "commitSeconds", "commitCount"]

if arg in ["CONFIGURE", "INSTALL"]: actions.configure(prop_name, prop_list) 
luceneProperties = getProperties(prop_name, prop_list)

if arg in ["CONFIGURE", "INSTALL"]:
    actions.checkNoErrors()

if arg == "INSTALL":           
       
    actions.installFile("lucene.properties")
    
    try:           
        uninstall()
        ovfiles = []
        if os.path.exists("logback.xml"): ovfiles.append(["logback.xml", "WEB-INF/classes"])
        actions.deploy(deploymentorder=80, files=ovfiles)
    except Exception, e:
        abort(str(e))
                
if arg == "UNINSTALL":        
    actions.removeFile(prop_name)
 
    try:
        uninstall()
    except Exception, e:
        abort(str(e))       
    
            
    
